### ISSUE TITLE
CallBack Bug

### ISSUE THREAD

**Issue by momedjussub** [PayGate/PayBatch_PayHost_WHMCS#4]
Hi!

Bug on the callback, please check this screen https://prnt.sc/pr0e01

[01-Nov-2019 09:49:25 Africa/Maputo] [WHMCS Application] ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'recordval' cannot be null in /home/xxxxx/public_html/vendor/illuminate/database/Connection.php:441 Stack trace: #0 /home/xxxxxx/public_html/vendor/illuminate/database/Connection.php(441): PDOStatement->execute(Array) #1 /home/xxxxxx/public_html/vendor/illuminate/database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `tb...', Array) #2 /home/xxxxxx/public_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('insert into `tb...', Array, Object(Closure)) #3 /home/xxxxx/public_html/vendor/illuminate/database/Connection.php(442): Illuminate\Database\Connection->run('insert into `tb...', Array, Object(Closure)) #4 /home/xxxx/public_html/vendor/illuminate/database/Connection.php(398): Illuminate\Database\Connection->statement('insert into `tb...', Array) #5 /home/xxxxx/public_html/vendor/illuminate/database/Query/Builder.php(2039): Illuminate\Database\Connection->insert('insert into `tb...', Array) #6 /home/xxxxx/public_html/modules/gateways/callback/payhostpaybatch.php(176): Illuminate\Database\Query\Builder->insert(Array) #7 {main}  Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'recordval' cannot be null (SQL: insert into `tblpayhostpaybatch` (`recordtype`, `recordid`, `recordval`) values (clientdetail, 2230, )) in /home/xxxxx/public_html/vendor/illuminate/database/Connection.php:713 Stack trace: #0 /home/xxxxxx/public_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('insert into `tb...', Array, Object(Closure)) #1 /home/xxxxx/public_html/vendor/illuminate/database/Connection.php(442): Illuminate\Database\Connection->run('insert into `tb...', Array, Object(Closure)) #2 /home/xxxxx/public_html/vendor/illuminate/database/Connection.php(398): Illuminate\Database\Connection->statement('insert into `tb...', Array) #3 /home/xxxx/public_html/vendor/illuminate/database/Query/Builder.php(2039): Illuminate\Database\Connection->insert('insert into `tb...', Array) #4 /home/xxxxxxx/public_html/modules/gateways/callback/payhostpaybatch.php(176): Illuminate\Database\Query\Builder->insert(Array) #5 {main} {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'recordval' cannot be null (SQL: insert into `tblpayhostpaybatch` (`recordtype`, `recordid`, `recordval`) values (clientdetail, 2230, )) at /home/xxxxxx/public_html/vendor/illuminate/database/Connection.php:713, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'recordval' cannot be null at /home/xxxxx/public_html/vendor/illuminate/database/Connection.php:441)"} []

**Comment by RBAtkins0n** [comment]
Thanks @momedjussub,

Looking into this.

**Comment by momedjussub** [comment]
> Thanks @momedjussub,
> 
> Looking into this.

Hi

Any update?

**Comment by RBAtkins0n** [comment]
Hi @momedjussub, 

Thank you for your patience, kindly try v1.0.3 per #5 for this issue (as well).
